apiVersion: 1
deleteDatasources:
  - name: connector-monitor-mysql
    orgId: 1
datasources:
  - name: connector-monitor-mysql
    uid: connector-monitor-mysql
    type: mysql
    access: proxy
    url: mysql:3306
    user: grafana
    database: connector_monitor
    secureJsonData:
      password: grafana
    secureJsonDataConfirm:
      password: grafana
    jsonData:
      authType: basic
      tlsSkipVerify: true
